# Generated by Django 2.2.2 on 2019-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_token', models.CharField(max_length=50)),
                ('app', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
