# Generated by Django 2.2.2 on 2019-06-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientapp',
            table='client_app',
        ),
    ]
